### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by Burton** [JoshData/cotaskme#12]
For account creation.

**Comment by Burton** [comment]
How do we notify people of new items? We shouldn't tweet them. We won't be able to send DMs unless they follow us. We don't be able to send them emails unless they provide us the address separately.

**Comment by JoshData** [comment]
I think we get their email address when they log in.

**Comment by Burton** [comment]
Yeah, I realized last night that this would be necessary if we're going to allow people to task based on email address.
