### ISSUE TITLE
Simplifying Finished/Closed

### ISSUE THREAD

**Issue by JoshData** [JoshData/cotaskme#17]
What do you think about this-

I think I put in the closed state as a way of representing that when tasks are done, the assigner usually has to do something (e.g. review it for quality) and the assigner would close the task when that step is done.

Instead of that, we could allow the recipient to open a new "is this okay?" task at the time of finishing a task. The original task would go to Finished at that would be the end of that task, and the _assigner_ would get a _new_ task asking him to acknowledge that the original thing is now back in his court for review. This would also create interesting threads connecting tasks.

Alternatively (or in addition), the assigner could mark a task as "create a new task for me when this is finished". So when the recipient finishes the task, the assigner automatically gets a new task in his inbox reminding him to do whatever he has to do next with that task.

**Comment by Burton** [comment]
The last part of that might work. Perhaps sending a task to another person gives you the option of verifying. If the task in question is completed and it creates a new task, what if the person who created the original task thinks their partner's work is NOT okay?

**Comment by JoshData** [comment]
I guess you could open a third task "please re-do this it was no good". Or you could force the original task to revert to its new-in-inbox state --- but that might be a surprise for the recipient ("I thought I finished this task").

After posting this issue, I also thought maybe the verify step is handled just by notifications. If I assign a task to you, I get a notification when you mark it finished. That's when I can decide to add a new task for myself to verify it. I might use the notification as a reminder to me that I need to look at the result of the task. But this is maybe why I like the idea of building in the verification step into the task list and not the notifications, so that notifications don't become essentially another type of task.
